name: iOS Build

on:
  push:
    branches: [ "main" ] # 只有当你向 main 分支提交代码时才触发

jobs:
  build:
    runs-on: macos-latest # 使用 GitHub 提供的最新 macOS 虚拟机

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Configure iOS Project # <--- 添加这一步，强制生成 iOS 工程文件
        run: flutter create --platforms=ios .

      - name: Build IPA (Unsigned)
        run: |
          flutter build ios --release --no-codesign
          mkdir -p Payload
          # 自动寻找编译出的 .app 并放入 Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r my-browser.ipa Payload

      - name: Upload Artifact  # <--- 必须确保有这一步
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa       # 下载时显示的名字
          path: my-browser.ipa # 要上传的文件路径
